/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#973100",
        "primary-container": "#c04000",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffe9e3",
        "primary-fixed": "#ffdbcf",
        "primary-fixed-dim": "#ffb59b",
        "on-primary-fixed": "#380d00",
        "on-primary-fixed-variant": "#812800",
        "secondary": "#5e5f5d",
        "secondary-container": "#e0e0dd",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#626361",
        "secondary-fixed": "#e3e2e0",
        "secondary-fixed-dim": "#c7c6c4",
        "tertiary": "#004cba",
        "tertiary-container": "#0062ec",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#e9edff",
        "tertiary-fixed": "#dae2ff",
        "tertiary-fixed-dim": "#b2c5ff",
        "background": "#fcf9f8",
        "on-background": "#1c1b1b",
        "surface": "#fcf9f8",
        "on-surface": "#1c1b1b",
        "surface-variant": "#e5e2e1",
        "on-surface-variant": "#594139",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "outline": "#8d7167",
        "outline-variant": "#e1bfb4",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1.0rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "unit": "4px",
        "container-margin": "20px",
        "gutter": "16px"
      },
      fontFamily: {
        sans: ["Public Sans", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        "headline-lg": ["Public Sans", "sans-serif"],
        "headline-md": ["Public Sans", "sans-serif"],
        "headline-xl": ["Public Sans", "sans-serif"],
        "label-md": ["Public Sans", "sans-serif"],
        "label-sm": ["Public Sans", "sans-serif"],
      }
    },
  },
  plugins: [],
}
